name: Signed Builds

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: gradle/gradle-build-action@v3.1.0
      - run: gradle assembleRelease

      - uses: ilharp/sign-android-release@v1.0.4
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 33.0.0

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: Signed apks
          path: app/build/outputs/apk/release/*-arm64-v8a-release-signed.apk
